In [8]:
import numpy as np
import matplotlib.pyplot as plt
import torch

torch.manual_seed(37)


In [9]:
x=torch.rand(5,3)
x

tensor([[0.7911, 0.6419, 0.8091],
        [0.1659, 0.3555, 0.6189],
        [0.9651, 0.2761, 0.7416],
        [0.6938, 0.1613, 0.1365],
        [0.4800, 0.9127, 0.8418]])

In [10]:
torch.cuda.is_available()

True

In [14]:
torch.version.cuda

'12.8'

In [16]:
!nvidia-smi

Mon Nov 17 16:48:18 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 572.61                 Driver Version: 572.61         CUDA Version: 12.8     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3060 ...  WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   52C    P8             13W /   95W |     119MiB /   6144MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [71]:
# Creating a tensor 

# Empty tensor contains random values
empty_tensor=torch.empty(3,2)
print(empty_tensor)

# Zeros tensor
zeros_tensor=torch.zeros(3,3)
print(zeros_tensor)

# Ones Tensor
ones_tensor=torch.ones(3,2)
print(ones_tensor)

# Fill tensor
full_tensor=torch.full([3,2],4,dtype=torch.float16)
print(full_tensor)

# arange(start,end,step)
range_tensor=torch.arange(1,30,5)
print(rand_tensor)

# Linspace (start,end,step): uniform space between numbers
linspace_tensor=torch.linspace(1,20,30)
print(linspace_tensor)

# like another matrix : with same shape as another matrix
sample=torch.rand(3,5)
my_zeros=torch.zeros_like(sample # Zeros tensor with same shape of another tensor

print(sample.shape,my_zeros.shape)



tensor([[2.3694e-38, 2.3694e-38],
        [2.3694e-38, 2.3694e-38],
        [2.3694e-38, 2.3694e-38]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[4., 4.],
        [4., 4.],
        [4., 4.]], dtype=torch.float16)
tensor([[[0.0959, 0.6911, 0.3321, 0.3449],
         [0.1966, 0.8259, 0.0901, 0.6670],
         [0.3490, 0.4521, 0.4524, 0.8921]]])
tensor([ 1.0000,  1.6552,  2.3103,  2.9655,  3.6207,  4.2759,  4.9310,  5.5862,
         6.2414,  6.8966,  7.5517,  8.2069,  8.8621,  9.5172, 10.1724, 10.8276,
        11.4828, 12.1379, 12.7931, 13.4483, 14.1034, 14.7586, 15.4138, 16.0690,
        16.7241, 17.3793, 18.0345, 18.6897, 19.3448, 20.0000])
torch.Size([3, 5]) torch.Size([3, 5])


In [82]:
# Attributes of tensors:
data=[[1,2,5,6,2,32],[3,4,6,7,9,34]]
data_tensor=torch.tensor(data,dtype=torch.float32)

print(f"Shape: {data_tensor.shape} Size:{data_tensor.size()}")
print(f"Dimension: {data_tensor.ndim} ")
print(f"No of elements: {data_tensor.numel()}")
print(f"Flatten : {torch.flatten(data_tensor)}")

print(f"Reshape : {data_tensor.reshape(3,4)}")
print(f"Data Type: {data_tensor.dtype}")
print(f"Device: {data_tensor.device}")



Shape: torch.Size([2, 6]) Size:torch.Size([2, 6])
Dimension: 2 
No of elements: 12
Flatten : tensor([ 1.,  2.,  5.,  6.,  2., 32.,  3.,  4.,  6.,  7.,  9., 34.])
Reshape : tensor([[ 1.,  2.,  5.,  6.],
        [ 2., 32.,  3.,  4.],
        [ 6.,  7.,  9., 34.]])
Data Type: torch.float32
Device: cpu


tensor([ 1.,  2.,  5.,  6.,  2., 32.,  3.,  4.,  6.,  7.,  9., 34.])

In [47]:
# Random arrays:

rand_tensor=torch.rand(1,3,4)
print(rand_tensor)

zeros_tensor=torch.zeros(3,3)
print(zeros_tensor)

ones_tensor=torch.ones(3,5)
print(ones_tensor)



tensor([[[0.0959, 0.6911, 0.3321, 0.3449],
         [0.1966, 0.8259, 0.0901, 0.6670],
         [0.3490, 0.4521, 0.4524, 0.8921]]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


In [48]:
# sending our data from cpu to gpu 

zeros_at_cpu=torch.zeros(3,3)

# getting device with tensor.device pproperty
print(zeros_at_cpu.device)
device="cuda" if torch.cuda.is_available() else "cpu"

# changing device  with tensor.to(device)  function
zeros_at_gpu=zeros_at_cpu.to(device)

print(zeros_at_gpu.device)


cpu
cuda:0


True